=== robertsmith2018/XML.DTD.XSD/cours2.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Cours (session, horaire+, professeur+, etudiant+)>
<!ELEMENT session (#PCDATA)>
<!ELEMENT horaire (#PCDATA)>
<!ELEMENT professeur (nom, prenom, courriel)>
<!ELEMENT etudiant (nom, prenom, courriel)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT courriel (#PCDATA)>

<!ATTLIST Cours sigle CDATA "" >
<!ATTLIST Cours nom CDATA "" >

<!ATTLIST professeur code CDATA "" >
<!ATTLIST etudiant numeroAdmission CDATA ""  >

=== robertsmith2018/XML.DTD.XSD/cours2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Cours SYSTEM "cours2.dtd">
	<Cours sigle="420-111-GG" nom="Technologies XML">
		<session>A2028</session>
		<horaire>Lundi 8h-11h</horaire>
		<horaire>Mercredi 8h-11h</horaire>
		<horaire>Vendredi 12h-15h</horaire>
		<professeur code="552">
			<nom>Fostine</nom>
			<prenom>kerlyne</prenom>
			<courriel>k.fostine@cgodin.qc.ca</courriel>
		</professeur>
		<professeur code="553">
			<nom>Derbali</nom>
			<prenom>Lotfi</prenom>
			<courriel>l.derbali@cgodin.qc.ca</courriel>
		</professeur>
		<etudiant numeroAdmission="562565">
			<nom>Assaker</nom>
			<prenom>Rabih</prenom>
			<courriel>a.rabih@cgodin.qc.ca</courriel>
		</etudiant>
		<etudiant numeroAdmission="562566">
			<nom>Benameur</nom>
			<prenom>Otmane</prenom>
			<courriel>b.Otmane@cgodin.qc.ca</courriel>
		</etudiant>
		<etudiant numeroAdmission="562567">
			<nom>Chitou</nom>
			<prenom>Chams</prenom>
			<courriel>c.chams@cgodin.qc.ca</courriel>
		</etudiant>
		<etudiant numeroAdmission="562568">
			<nom>Cruz</nom>
			<prenom>Edgar</prenom>
			<courriel>c.cruz@cgodin.qc.ca</courriel>
		</etudiant>
		
	</Cours>
