=== robertsmith2018/XML.DTD.XSD/XMLSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" > 
	
	<xs:element name="Cours">
	 	<xs:complexType>
	 		<xs:sequence>
	 			<xs:element name="session" type="xs:string" />
	 			<xs:element name="horaire" type="xs:string" maxOccurs="unbounded" />
	 			<xs:element name="professeur" maxOccurs="unbounded">
	 				<xs:complexType>
	 					<xs:sequence>
	 						<xs:element name="nom" type="xs:string" />
	 						<xs:element name="prenom" type="xs:string" />
	 						<xs:element name="courriel" type="xs:string" />
	 					</xs:sequence>
	 					<xs:attribute name="code" type="xs:integer" use="required" />
	 				</xs:complexType>
	 			</xs:element>
	 			<xs:element name="etudiant" maxOccurs="unbounded">
	 				<xs:complexType>
	 					<xs:sequence>
	 						<xs:element name="nom" type="xs:string" />
	 						<xs:element name="prenom" type="xs:string" />
	 						<xs:element name="courriel" type="xs:string" />
	 					</xs:sequence>
	 					<xs:attribute name="numeroAdmission" type="xs:integer" use="required" />
	 				</xs:complexType>
	 			</xs:element>

	 		</xs:sequence>
	 		<xs:attribute name="sigle" type="xs:string" use="required"/>
	 		<xs:attribute name="nom" type="xs:string" use="required"/>
	 	</xs:complexType>
	
	</xs:element>
</xs:schema>

=== robertsmith2018/XML.DTD.XSD/cours.xml
<?xml version="1.0" encoding="UTF-8"?>

<Cours sigle="420-111-GG" nom="Technologies XML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XMLSchema.xsd" >
	<session>A2028</session>
	<horaire>Lundi 8h-11h</horaire>
	<horaire>Mercredi 8h-11h</horaire>
	<horaire>Vendredi 12h-15h</horaire>
	<professeur code="562">
		<nom>Fostine</nom>
		<prenom>kerlyne</prenom>
		<courriel>k.fostine@cgodin.qc.ca</courriel>
	</professeur>
	<professeur code="5555355">
		<nom>Derbali</nom>
		<prenom>Lotfi</prenom>
		<courriel>l.derbali@cgodin.qc.ca</courriel>
	</professeur>
	<etudiant numeroAdmission="562565">
		<nom>Assaker</nom>
		<prenom>Rabih</prenom>
		<courriel>a.rabih@cgodin.qc.ca</courriel>
	</etudiant>
	<etudiant numeroAdmission="562566">
		<nom>Benameur</nom>
		<prenom>Otmane</prenom>
		<courriel>b.Otmane@cgodin.qc.ca</courriel>
	</etudiant>
	<etudiant numeroAdmission="562567">
		<nom>Chitou</nom>
		<prenom>Chams</prenom>
		<courriel>c.chams@cgodin.qc.ca</courriel>
	</etudiant>
	<etudiant numeroAdmission="562568">
		<nom>Cruz</nom>
		<prenom>Edgar</prenom>
		<courriel>c.cruz@cgodin.qc.ca</courriel>
	</etudiant>

</Cours>
